(use-modules (srfi srfi-1))

(define (binary-search values target)
  (let loop ((low 0) (high (- (vector-length values) 1)))
    (if (> low high)
        #f
        (let* ((middle (quotient (+ low high) 2))
               (value (vector-ref values middle)))
          (cond ((= value target) middle)
                ((< value target) (loop (+ middle 1) high))
                (else (loop low (- middle 1))))))))

(define graph '((A B C) (B D) (C E) (D) (E)))
(define (stable-insertion-sort items less?)
  (define (insert item sorted)
    (cond ((null? sorted) (list item))
          ((less? item (car sorted)) (cons item sorted))
          (else (cons (car sorted) (insert item (cdr sorted))))))
  (let loop ((rest items) (sorted '()))
    (if (null? rest)
        sorted
        (loop (cdr rest) (insert (car rest) sorted)))))

(define (bfs start)
  (let loop ((queue (list start)) (seen (list start)) (result '()))
    (if (null? queue)
        (reverse result)
        (let* ((node (car queue))
               (neighbors (cdr (assq node graph)))
               (fresh (filter (lambda (next) (not (memq next seen))) neighbors)))
          (loop (append (cdr queue) fresh)
                (append seen fresh)
                (cons node result))))))

(define sorted (stable-insertion-sort '(5 2 8 2 1) <))
(define records '((1 . "one-a") (2 . "two") (1 . "one-b")))
(define stable (stable-insertion-sort records (lambda (left right) (< (car left) (car right)))))
(format #t "sorted=~{~a~^,~}~%" sorted)
(format #t "stable=~{~a~^,~}~%" (map cdr stable))
(format #t "binary-search(5)=~a~%" (binary-search #(1 2 2 5 8) 5))
(format #t "bfs=~{~a~^,~}~%" (bfs 'A))
(display "style=tail recursion plus SRFI sequences\n")
