(format t "=== Common Lisp Adjustable Vector ===~%")
(let ((vec (make-array 2 :adjustable t :fill-pointer 0)))
  (vector-push-extend 10 vec)
  (vector-push-extend 20 vec)
  (vector-push-extend 30 vec)
  (assert (= (length vec) 3))
  (assert (= (aref vec 1) 20))
  (format t "Vector length: ~a, elements: ~a ~a ~a~%" (length vec) (aref vec 0) (aref vec 1) (aref vec 2))
  (format t "Common Lisp Dynamic Array tests passed successfully.~%"))
